### PR TITLE
Fix some castings of `.pi`

### PR DESCRIPTION
**Pull request by LaurentiuUngur**

### CODE REVIEW

**Comment by PGLongo** [comment]
I don't understand, maybe some issue with Travis and swiflint. I will try manually today in the evening

**Comment by LaurentiuUngur** [comment]
Indeed. Please try and let me know. Thanks !

**Comment by PGLongo** [comment]
Thanks again!

**Comment by LaurentiuUngur** [comment]
Thank you too for making this library !

**Comment by PGLongo** [comment]
It's not mine. @pkluz make this library. I'm a huge fan and I try to maintain this library

**Comment by PGLongo** [comment]
I don't understand the reason, but you are the 4th asking this minor release. So here the new version

screen shot 2017-03-31 at 18 34 48

**Pull request merged**
