### PR TITLE
Adding support for macOS by using shims

### PR DESCRIPTION
**Pull request by Fab1n**
Adds complete support for using PKHUD under macOS.
Changes are almost all additive and held simple by adding a shim file to bring both platform APIs together. 

Use the demo app to check if all huds work smoothly and do what they say.
Then please check logic and code style and see if it all fits.

### CODE REVIEW

**Comment by PGLongo** [comment]
Thanks for this HUGE PR. I will give a try ASAP.

**Comment by Fab1n** [comment]
some progress there?

**Comment by PGLongo** [comment]
Not so many.  I thinks it would be better to change the branch to [feature/macOS (https://github.com/pkluz/PKHUD/tree/feature/macOS) and work there for the next release.

**Comment by Fab1n** [comment]
closing, due to working in a feature branch where this (https://github.com/pkluz/PKHUD/pull/141) PR tries to add the changes

**Comment by PGLongo** [comment]
Thanks a lot

**Pull request closed without merging**
