### PR TITLE
Add compatibility to Swift 4.2 on Xcode 10 GM

### PR DESCRIPTION
**Pull request by edisonlsm**
Fixed the 2 errors thrown by Xcode 10 GM on 5.1.0 version of PKHUD with Swift version set to 4.2.

Both fixes required minimal changes (just one init and one enum that got renamed).

### CODE REVIEW

**Comment by anthonypuppo** [comment]
Can we get this merged soon please?

**Comment by edisonlsm** [comment]
Hey @pkluz, @PGLongo is it possible to merge this?

Since the .swift-version file is deprecated and the podspec does not contain a swift_version property PKHUD will not compile by default on a Swift 4.2 project (CocoaPods will set PKHUD to Swift 4.2 and it will throw two compile errors)

**Comment by mihailsalari** [comment]
@pkluz please update to Swift 4.2 version.

**Comment by maurovc** [comment]
@PGLongo can we get this PR merged? Thanks!

**Comment by PGLongo** [comment]
Done. Sorry for the delay

**Comment by giofid** [comment]
Can you please release a new version with this merge? Thank you

**Comment by edisonlsm** [comment]
Thanks, @PGLongo !

Are you planning to make a new release anytime soon? I would really appreciate that :)

Also, when you make a new release, I think it might be a good idea to add a `s.swift_version = '4.2'` to the podspec in order to avoid compatibility issues when the next version of Swift gets released!

**Comment by anthonypuppo** [comment]
Still need a new release created.

**Comment by edisonlsm** [comment]
Hi @PGLongo any chance you can make a new release so we can install it properly without needing to use `:git =>` on the Podfile?

**Comment by PGLongo** [comment]
I'm working on it

**Comment by anthonypuppo** [comment]
@PGLongo Change your build setting "Swift 3 @objc Inference" to "Default" (Project -> Build Settings tab -> search term "inference").

**Comment by PGLongo** [comment]
Thanks @anthonypuppo and everyone

screenshot 2018-09-28 at 14 17 21

**Pull request merged**
