### PR TITLE
Custom font added

### PR DESCRIPTION
**Pull request by Hassaniiii**
now you can set custom fonts for you HUD. because it has default value, this feature is considered as optional. so your previous codes won't affected, while you can update them to use new fonts

### CODE REVIEW

**Comment by PGLongo** [comment]
Hi @Hassaniiii and thanks for the PR. Unfortunately I can't merge this because we are discussing about a configurable HUD  behaviour and this is argument of another issue (#130).

There are a lot of possible configurations for the HUD and is not reasonable to have function with all the parameters, today we add the font but tomorrow could be:

1. Color
1. Size
1. Alignement
1. ...

**Comment by Hassaniiii** [comment]
Hi, thanks for your reply. do you want to start a configuration branch to implement all these features? I can and like to do all of them step by step

**Comment by PGLongo** [comment]
I will start soon. Have a look to #157

**Comment by Hassaniiii** [comment]
I'm interesting to help you for #157<https://github.com/pkluz/PKHUD/issues/157>, but I'm new on slack. I thinks I should enter my email in slack in "Find your team" section, right?


--
Regards,
Hassan Shahbazi
Senior iOS Developer
e: h-shahbazi@outlook.com<mailto:-shahbazi@outlook.com>
t: +989368852535
skype: hassan.shahbazi.sy

On Farvardin 13, 1396 AP, at 00:07, Piergiuseppe Longo <notifications@github.com<mailto:notifications@github.com>> wrote:

will start soon. Have a look

**Pull request closed without merging**
