### PR TITLE
View based HUD, plus support for macOS

### PR DESCRIPTION
**Pull request by Fab1n**
Changes window based HUD for a view based implementation. It is possible to specify a view on where to present the HUD. Also this was essential for macOS support.

macOS support is done through shimming the iOS APIs to change the master project as little as possible and make the macOS specifics as compatible as possible. 
In some circumstances there can be glitches on macOS. We should optimise and fix eventual glitches over filing issues.

Otherwise please test and comment on this PR. Would be happy to integrate this into master as soon as possible.

### CODE REVIEW

**Comment by PGLongo** [comment]
I'm looking at this PR. If you agree with me I would like to make a separate PR and I will merge as soon as possible (I hope today) the view based feature and then we can discuss about macOs

**Comment by PGLongo** [comment]
I've used git cherry-pick b09fe2a21cc75c126f0652f19f0cf90318157b7d and everything seems to be  ok. So @Fab1n  & @angerman  let me know what do you think.

**Comment by PGLongo** [comment]
I saw some little problems on MacOS. I really think that would be better to work on a separated branch and then merge. 

success

**Comment by angerman** [comment]
@PGLongo Once b09fe2a is in `master`, it should be trivial to rebase the changes (in a separate branch) onto the `master` branch, which would make 28bc819 unnecessary. I hope @Fab1n has time to look into the drawing issue and do the rebase.

**Comment by PGLongo** [comment]
Done. Thanks @Fab1n and @angerman

**Comment by PGLongo** [comment]
Thanks guys!
screen shot 2016-12-09 at 13 03 08

**Pull request closed without merging**
