### PR TITLE
Fixes for Xcode6.3b4

### PR DESCRIPTION
**Pull request by piercifani**

### CODE REVIEW

**Comment by anthonycastelli** [comment]
Any chance this can get merged in?

**Comment by lincode** [comment]
Please merge this pr.

**Comment by anthonycastelli** [comment]
@lincode I forked it and hack fixed it for the time being. https://github.com/anthonycastelli/PKHUD Feel free to have a look at it!

**Comment by lincode** [comment]
@anthonycastelli Thx.

**Comment by anthonycastelli** [comment]
@lincode No problem.

**Pull request closed without merging**
