### PR TITLE
Exposing old objc API methods using #selector to @objc

### PR DESCRIPTION
**Pull request by thibauddavid**
Bumped pod to 4.2.4

### CODE REVIEW

**Comment by PGLongo** [comment]
Hi @thibauddavid, thanks for your PR. Can you explain the reason?

**Comment by thibauddavid** [comment]
Sure :)

As specified within [Swift4 evolutions](https://github.com/apple/swift-evolution/blob/master/proposals/0160-objc-inference.md#nsobject-derived-classes-no-longer-infer-objc) , 

```
A declaration within an NSObject-derived class will no longer infer @objc
```

As a result, this code would not compile otherwise when using xCode9 along with Swift4, because some old objC API using selectors are used, eg: 

```
NotificationCenter.default.addObserver(self,
            selector: #selector(PKHUD.willEnterForeground(_:)),
            name: NSNotification.Name.UIApplicationWillEnterForeground,
            object: nil)
```

**Comment by PGLongo** [comment]
Ok understood. 

But please don't bump the version to 4.2.4, because the swift4 release is intended like a beta and you should specify the branch and not the version to download it. You should bump the version only for changes in the branch master

**Comment by thibauddavid** [comment]
Reverted podspec and deleted 4.2.4 . Cheers

**Pull request merged**
