### PR TITLE
Updated README.md for Swift3

### PR DESCRIPTION
**Pull request by PGLongo**
Added instructions for installing PKHUD with Swift3 support.

I don't agree with you about duplicating the pod. Other projects like Alamofire, a very small project (obviously I'm just kidding) don't do that.

### CODE REVIEW

**Comment by jshier** [comment]
Regarding the pod versions, you can keep older versions around using tags and update them both using CocoaPods. That's how we update both Alamofire 3.5.1 and 4.0.0 at the same time through the same pod name.

**Comment by seifeet** [comment]
It makes sense to merge this pull requests since now when you do pod "PKHUD" you get Swift 2.3 version.

**Comment by robertofrontado** [comment]
This should be merged

**Comment by PGLongo** [comment]
Actually me and @pkluz are discussing about having only one podspec or not.

**Comment by pkluz** [comment]
I'd prefer having only one Podspec and do Swift compatibility via versions/tags.

**Comment by robertofrontado** [comment]
That sounds better to me

**Comment by PGLongo** [comment]
Just released PKHUD (4.0.0) 
screen shot 2016-10-27 at 18 16 56

**Pull request merged**
