### PR TITLE
allow to use it with only ‘title’ argument

### PR DESCRIPTION
**Pull request by Speakus**

### CODE REVIEW

**Comment by PGLongo** [comment]
Thanks @Speakus for the PR. I think your PR is correct but I would like to give a try before merging it. Probably during this week end

**Comment by PGLongo** [comment]
Sorry but I've this error

screen shot 2016-12-09 at 11 20 39

**Comment by Speakus** [comment]
I'm sorry for this PR - It's my fault. Please ignore it.

**Comment by PGLongo** [comment]
Don't worry. Thanks anyway

**Pull request closed without merging**
