### PR TITLE
Feature/view based

### PR DESCRIPTION
**Pull request by Fab1n**
With these changes the huds are now view based, not window based anymore.

When showing a hud with the .show() method there is now an optional parameter called :onView to give a view where to present the hud on. 
If no view is given it falls back to UIApplication.sharedApplication().keyWindow. 
The hud is presented at index 9999. There should be enough room for other views to display underneath and above the hud.

Also all layouting is now done with constraints using the new constraint api introduced in iOS 9 which explains, why I raised the deployment target to iOS 9. 
If we want iOS 8 back, then we need to change the layouting stuff to the old constraint language.

### CODE REVIEW

**Comment by Fab1n** [comment]
The view based HUD display could be done like this. 
It is a relatively easy implementation. Please have a look at it and tell me if it is the right direction.

**Comment by domhof** [comment]
I would like to use PKHUD in an app extension, so this is exactly what I need, except for the iOS 9 limitation (I want to support iOS 8 as well). Is it possible to split up this feature branch into two separate ones, e.g. feature/view_based and feature/new_constraint_api?

**Comment by Fab1n** [comment]
I think we can switch back to old constraint syntax. I will give it a shot

**Comment by Fab1n** [comment]
should fix #79 except the current PKHUD.podfile repo reference

**Pull request closed without merging**
