### PR TITLE
SPM support

### PR DESCRIPTION
**Pull request by arturgrigor**

### CODE REVIEW

**Comment by PGLongo** [comment]
Thank you @arturgrigor.

**Comment by PGLongo** [comment]
@arturgrigor I've this error:

image

I'm doing something wrong?

**Comment by arturgrigor** [comment]
[PKHUD SPM Test.zip](https://github.com/pkluz/PKHUD/files/5238796/PKHUD.SPM.Test.zip)

@PGLongo I'm not sure, but you can check and run this small demo with Xcode 12 and everything should work just fine.

**Comment by PGLongo** [comment]
Please can you try to install PKHUD with SPM?

**Comment by arturgrigor** [comment]
@PGLongo 

I did that by running the following commands:
```sh
mkdir pkhud-spm-test
cd pkhud-spm-test
swift package init
vi Package.swift; here I added a ".package(url: "https://github.com/pkluz/PKHUD.git", .upToNextMinor(from: "5.4.0"))," to the dependencies section, and listed "PKHUD" in the "pkhud-spm-test" target's dependencies
swift package update
swift package generate-xcodeproj
```

And everything worked just fine.

Note: You should make sure that Xcode 12 is selected for the Command Line Tools.

**Comment by arturgrigor** [comment]
@PGLongo I got that same problem earlier on a build machine because they are still using Xcode 11 and this library requires Xcode 12 due to the images that come with it and bundling resources into the library is only available in Xcode 12.

**Pull request merged**
